services:
  - type: web
    name: 91ClubPredictorBot
    env: python
    plan: free
    branch: main
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    autoDeploy: true
